import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} min-h-screen bg-[var(--bg)] text-[var(--fg)]`}>
        {/* global top navigation */}
        <TopNav />
        <main className="mx-auto max-w-6xl px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
